

 --SE RESPALDA PIELES QUE HAY ACTUALMENTE EN LA TABLA RP_SC EN TABLA RP_SC_HIDE_DELETE 
--INSERT INTO RP_SC_HIDE_DELETE( 
--		[CDATE],[COLOUR],[LOT],[HIDE],[SQF],[TAGNO],[YARDAS],[YLB],[PESO],[TYPE],[MOVEMENT],[K_CLASIFICACION]
--		)
--SELECT GETDATE(),[COLOUR],[LOT],[HIDE],[SQF],[TAGNO],[YARDAS],[YLB],[PESO],[TYPE],MOVEMENT,[K_CLASIFICACION] 
--FROM RP_SC (NOLOCK) 
--WHERE LTRIM(RTRIM(COLOUR)) = 'FMCKPD2'
--AND MOVEMENT IN ('MOB', 'MHI') 


------DELETE RP_SC WHERE LTRIM(RTRIM(COLOUR)) = 'FMCKPD2'AND MOVEMENT IN ('MOB', 'MHI') 

-- SE CARGAN LAS PIELES DE LOS DETALLADOS
--INSERT INTO RP_SC( 
--		[CDATE],[COLOUR],[LOT],[HIDE],[SQF],[TAGNO],[YARDAS],[YLB],[PESO],[TYPE],[MOVEMENT],[K_CLASIFICACION]
--		)
--SELECT GETDATE(),LTRIM(RTRIM([COLOUR])),LTRIM(RTRIM([LOT])),LTRIM(RTRIM([HIDE])),LTRIM(RTRIM([SQF])),3881658, [YARDAS],[YLB],[PESO],'C','MOB',[K_CLASIFICACION]
--FROM RP_SC_FOLIO_TYPE_2
--WHERE LTRIM(RTRIM(COLOUR)) = 'FMCKPD2' 
--	AND TAGNO IN ( 3791601,3791602, 3791603, 3791604, 3791611 )


	SELECT * --[COLOUR], [LOT], [HIDE], [SQF], 3772650, 'C', 'MHI'
	FROM RP_SC_FOLIO_TYPE_2 (NOLOCK)
	WHERE LTRIM(RTRIM(COLOUR)) = 'FMCKPD2' 
	AND TAGNO IN ( 3791601,3791602, 3791603, 3791604, 3791611 )
	ORDER BY LOT, HIDE

	SELECT  LOT, HIDE, COUNT(*) AS N_DUPLICADA
	FROM RP_SC_FOLIO_TYPE_2 (NOLOCK)
	WHERE LTRIM(RTRIM(COLOUR)) = 'FMCKPD2' 
	AND TAGNO IN ( 3791601,3791602, 3791603, 3791604, 3791611 )
	GROUP BY  LOT, HIDE 
	HAVING COUNT(*)>1
	ORDER BY LOT, HIDE

	-- SE OBTIENE EL FOLIO DONDE SE VAN A CARGAR LAS PIELES
	SELECT * 
	FROM RP_SC 
	WHERE COLOUR = 'FNRUML8' AND MOVEMENT IN ( 'MOB', 'MHI' )
	--AND TAGNO = 3881658

	SELECT * FROM RP_Folios WHERE TAG = 3881658

	--- ////////// VALIDAR PIELES DUPLICADAS /////////////////////////////
	DECLARE @TBL_PIEL_MOB TABLE(
		LOT		VARCHAR(50),
		HIDE	VARCHAR(50),
		SQF		VARCHAR(50)		
	)

	INSERT INTO @TBL_PIEL_MOB
	SELECT LTRIM(RTRIM(LOT)), LTRIM(RTRIM(HIDE)), LTRIM(RTRIM(SQF))
	FROM RP_SC (NOLOCK)
	WHERE COLOUR = 'FNRUML8' AND MOVEMENT IN ( 'MOB', 'MHI' )

	INSERT INTO @TBL_PIEL_MOB
	SELECT LTRIM(RTRIM(LOT)), LTRIM(RTRIM(HIDE)), LTRIM(RTRIM(SQF))
	FROM RP_SC_FOLIO_TYPE_2 (NOLOCK)
	WHERE COLOUR = 'FNRUML8' --AND MOVEMENT IN ( 'MOB', 'MHI' )
	AND TAGNO IN ( 3791637, 3791639, 3791644, 3791641, 3791645)

	SELECT  LOT, HIDE, COUNT(*) AS N_DUPLICADA
	FROM @TBL_PIEL_MOB 
	GROUP BY  LOT, HIDE 
	HAVING COUNT(*)>1
	ORDER BY LOT, HIDE

	SELECT * FROM @TBL_PIEL_MOB

	SELECT * FROM RP_SC (NOLOCK) 
	WHERE LOT = '67521' AND HIDE IN ('0823', '0824', '0825')	
	ORDER BY HIDE

	SELECT * FROM RP_SC_FOLIO_TYPE_2 (NOLOCK) 
	WHERE LTRIM(RTRIM(COLOUR)) = 'FNRUML8' 
	AND LOT = '67521' AND HIDE IN ('0823', '0824', '0825')	
	AND TAGNO IN ( 3791637, 3791639, 3791644, 3791641, 3791645)
	ORDER BY HIDE

		
	-- SE CARGAN LAS PIELES DE LOS DETALLADOS
	--INSERT INTO RP_SC( 
	--		[CDATE],[COLOUR],[LOT],[HIDE],[SQF],[TAGNO],[YARDAS],[YLB],[PESO],[TYPE],[MOVEMENT],[K_CLASIFICACION]
	--		)
	--SELECT GETDATE(),LTRIM(RTRIM([COLOUR])),LTRIM(RTRIM([LOT])),LTRIM(RTRIM([HIDE])),LTRIM(RTRIM([SQF])),3868921, [YARDAS],[YLB],[PESO],'C','MOB',[K_CLASIFICACION]
	--FROM RP_SC_FOLIO_TYPE_2
	--WHERE LTRIM(RTRIM(COLOUR)) = 'FNRUML8' 
	--AND TAGNO IN ( 3791637, 3791639, 3791644, 3791641, 3791645)

	SELECT  LOT, HIDE, COUNT(*) AS N_DUPLICADA
	FROM RP_SC (NOLOCK)
	WHERE LTRIM(RTRIM(COLOUR)) = 'FNRUML8' AND MOVEMENT = 'MOB'
	GROUP BY  LOT, HIDE 
	HAVING COUNT(*)>1
	ORDER BY LOT, HIDE
