



--DECLARE @VP_FOLIO_BASE INT = 0
--SELECT TOP 1 @VP_FOLIO_BASE = MAX(TAG) FROM RP_FOLIOS 

--SET @VP_FOLIO_BASE = @VP_FOLIO_BASE + 1

--EXECUTE [dbo].[PG_IN_RP_FOLIOS]		0, 0,
--									@VP_FOLIO_BASE, 'B', NULL, NULL, NULL
		

--INSERT INTO RP_SC( 
--		[CDATE],[COLOUR],[LOT],[HIDE],[SQF],[TAGNO],[YARDAS],[YLB],[PESO],[TYPE],[MOVEMENT],[K_CLASIFICACION]
--		)
--SELECT GETDATE(),'FGMPAX7',[LOT],[HIDE],[SQF],@VP_FOLIO_BASE,[YARDAS],[YLB],[PESO],'C','MHI',[K_CLASIFICACION]
--FROM RP_SC_FOLIO_TYPE_2 WHERE TAGNO = 3788274
					
SELECT * FROM RP_SC 
WHERE LOT = '401451'   
AND HIDE IN (SELECT HIDE FROM RP_SC_FOLIO_TYPE_2 WHERE TAGNO = 3788274  )
AND COLOUR = 'FWLPAX7'
AND TAGNO = 3793142

--DELETE FROM RP_SC 
--WHERE LOT = '401451'   
--AND HIDE IN (SELECT HIDE FROM RP_SC_FOLIO_TYPE_2 WHERE TAGNO = 3788274  )
--AND COLOUR = 'FWLPAX7'
--AND TAGNO = 3793142

SELECT * FROM RP_SC_FOLIO_TYPE_2 WHERE TAGNO = 3788274 

SELECT * FROM COLORES_CONTROLADOS

SELECT TOP 100 * FROM RP_SC WHERE COLOUR = 'FGMPAX7'