



--DECLARE @VP_FOLIO_BASE INT = 0
--SELECT TOP 1 @VP_FOLIO_BASE = MAX(TAG) FROM RP_FOLIOS 

--SET @VP_FOLIO_BASE = @VP_FOLIO_BASE + 1

--EXECUTE [dbo].[PG_IN_RP_FOLIOS]		0, 0,
--									@VP_FOLIO_BASE, 'B', NULL, NULL, NULL
		

--INSERT INTO RP_SC( 
--		[CDATE],[COLOUR],[LOT],[HIDE],[SQF],[TAGNO],[YARDAS],[YLB],[PESO],[TYPE],[MOVEMENT],[K_CLASIFICACION]
--		)
--SELECT TOP 1 CDATE,COLOUR,[LOT],  '0000','0000',@VP_FOLIO_BASE,[YARDAS],[YLB],[PESO],[TYPE],'MHI',[K_CLASIFICACION]
--FROM RP_SC WHERE TAGNO = 3797336
					
SELECT * FROM RP_SC WHERE TAGNO = 3797731
--DELETE RP_SC WHERE ID = 5096686

SELECT * FROM RP_SC 
WHERE LOT = '401451'   
AND HIDE IN (SELECT HIDE FROM RP_SC_FOLIO_TYPE_2 WHERE TAGNO = 3788274  )
AND COLOUR = 'FWLPAX7'
AND TAGNO = 3793142

SELECT * FROM RP_SC_FOLIO_TYPE_2 WHERE TAGNO = 3788274 

SELECT * FROM COLORES_CONTROLADOS

SELECT TOP 100 * FROM RP_SC WHERE COLOUR = 'FGMPAX7'
ORDER BY ID

--=========PARA PRUEBAS========================
USE DATA_02Pruebas
	----ALTER TABLE PIEL_LOG ADD COLOR_DESTINO VARCHAR(50) DEFAULT '' 

	--SELECT TOP 200 * FROM TIPO_PIEL_LOG WHERE K_TIPO_PIEL_LOG = 11
	--SELECT * FROM RP_FOLIOS WHERE TAG = 3795145174
	--delete invcre_sql where id = 71803

	SELECT * FROM RP_SC WHERE TAGNO = 3796708

	SELECT TOP 1000 * FROM PIEL_LOG WHERE FOLIO_DESTINO = 3796708

	SELECT * FROM RP_SC WHERE  LOT = '501041' AND HIDE = '0004' ORDER BY HIDE
	
	SELECT * FROM RP_SC_TEMP WHERE TAGNO = 3797567 


	SELECT  LTRIM(RTRIM(COLOUR)) , LTRIM(RTRIM(LOT)), SUM(CONVERT(DECIMAL(13,4),LTRIM(RTRIM(SQF))))
		FROM RP_SC 
		WHERE TAGNO = 3788363
		GROUP BY COLOUR, LOT

	SELECT TOP 100 * FROM	HIDESHDR_SQL WHERE  FILENO = '200924062920T1000002'      
	SELECT TOP 1000 * FROM	HIDESLIN_SQL WHERE  FILENO = '200924062920T1000002'  AND  PRINTED  = 1


	SELECT HIDESHDR_SQL.FILENO,HIDESLIN_SQL.HIDE,HIDESLIN_SQL.SQF,HIDESHDR_SQL.PLOT, 
	( CASE WHEN COLOR_DESTINO IS NULL OR COLOR_DESTINO = '' THEN PCOLOR ELSE COLOR_DESTINO END) AS pcolor,printed 
	from HIDESLIN_SQL
    INNER JOIN HIDESHDR_SQL On HIDESLIN_SQL.FILENO=HIDESHDR_SQL.FILENO 
    LEFT JOIN PIEL_LOG on CONVERT(INT, PLOT) = PIEL_LOG.LOTE 
	AND CONVERT(INT, HIDE) = PIEL_LOG.PIEL
	AND HIDESLIN_SQL.SQF = PIEL_LOG.SQF 
	AND K_TIPO_PIEL_LOG = 11
    where  HIDESHDR_SQL.FILENO='20201014165148' order by hide desc
	
  -- AGREGA A LA LOCACION DESTINO
SELECT * FROM	IMLSMST_SQL	WHERE	LTRIM(RTRIM(LOC))='MHI' AND	LTRIM(RTRIM(ITEM_NO))='FGMPAt5' --AND	LTRIM(RTRIM(SER_LOT_NO)) = '401451'
--QTY_ON_HAND = 4332.6000 - 399.9 = 3,932.7

SELECT * FROM	IMLSMST_SQL	WHERE	LTRIM(RTRIM(LOC))='MHI' AND	LTRIM(RTRIM(ITEM_NO))='FGMPAX7' --AND	LTRIM(RTRIM(SER_LOT_NO)) = '401451'
--ORIGINAL: QTY_ON_HAND = 0.0000 + 399.9 = 399.9


-- RESTA DE LA LOCACION ORIGEN
SELECT * FROM IMINVLOC_SQL WHERE LTRIM(RTRIM(LOC)) = 'MHI' AND	LTRIM(RTRIM(ITEM_NO)) = 'FWLPAX7'
--ORIGINAL: QTY_ON_HAND = 5544.3000 -  399.9  = 5,144.4

SELECT * FROM IMINVLOC_SQL WHERE LTRIM(RTRIM(LOC)) = 'MHI' AND	LTRIM(RTRIM(ITEM_NO)) = 'FGMPAX7'
-- QTY_ON_HAND = 311.8000 + 399.9  =711.7

SELECT top 10 * FROM IMLSTRX_SQL	WHERE LTRIM(RTRIM(ord_no)) = ( '4890859 ' )

SELECT top 10 * FROM IMINVTRX_SQL	WHERE LTRIM(RTRIM(ord_no)) = ( '4890859 ' )


select top 1000 * from IMINVTRX_SQL 
where  /*item_no = 'FNPJTX7  '    and*/ loc = 'MHI' /*AND ITEM_NO = 'FGMPAX7'*/  and trx_dt>='20201016'
AND doc_ord_no like '%14595'
order by trx_TM, ORD_NO desc

SELECT * FROM PIEL_LOG WHERE K_TIPO_PIEL_LOG = 11