
USE DATA_02Pruebas
--//////////////////INDICES CREADOS///////////////////////////////////////////////
--DROP INDEX UN_RP_SC_01_ID ON [RP_SC] 
--GO

-- CREATE NONCLUSTERED INDEX [UN_RP_SC_01_ID]
--ON [dbo].[RP_SC] ([CDATE],[MOVEMENT])
--INCLUDE ([COLOUR],[LOT],[HIDE],[SQF],[TAGNO],[TYPE],[K_CLASIFICACION])
--GO

--DROP INDEX [UN_RP_SC_01_COLOR] ON [RP_SC] 
--GO
-- CREATE NONCLUSTERED INDEX [UN_RP_SC_01_COLOR]
--ON [dbo].[RP_SC] ([COLOUR])
--INCLUDE ([LOT],[HIDE],[SQF],[TAGNO],[TYPE],[K_CLASIFICACION])
--GO
 
-- DROP INDEX [UN_RP_FOLIOS_01_TAG] ON [RP_FOLIOS] 
--GO
-- CREATE NONCLUSTERED INDEX [UN_RP_FOLIOS_TAG]
--ON [dbo].[RP_FOLIOS] ([TAG])
--INCLUDE (ID,STATUS,JOBNO, MACHINE)
--GO


-- DROP INDEX [UN_RP_FOLIOS_01_TAG] ON [RP_FOLIOS] 
--GO
-- CREATE NONCLUSTERED INDEX [UN_RP_FOLIOS_TAG]
--ON [dbo].[RP_FOLIOS] ([TAG])
--INCLUDE (ID,STATUS,JOBNO, MACHINE)
--GO
 --/////////////////////////////////////////////////////////////////

---- PIELES CON TYPO 2

SELECT * FROM RP_SC_FOLIO_TYPE_2
SELECT *  FROM RP_SC WHERE LTRIM(RTRIM(TYPE)) = '2'

SELECT DISTINCT RP_SC.* --INTO RP_SC_FOLIO_TYPE_2
 FROM RP_SC 
WHERE LTRIM(RTRIM(TYPE))  = ('2')
AND ID =4552422

--INSERT INTO RP_SC_FOLIO_TYPE_2( 
--		[CDATE],[COLOUR],[LOT],[HIDE],[SQF],[TAGNO],[YARDAS],[YLB],[PESO],[TYPE],[MOVEMENT],[K_CLASIFICACION]
--		)
-- SELECT CDATE,[COLOUR],[LOT],[HIDE],[SQF],[TAGNO],[YARDAS],[YLB],[PESO],[TYPE],[MOVEMENT],[K_CLASIFICACION]
-- FROM RP_SC   
-- WHERE LTRIM(RTRIM(TYPE))  = ('2')
--/////////////////////////////////////////////////////////////////

---- PIELES CON MOVIMIENTO NULL
SELECT  * FROM RP_SC
WHERE  LTRIM(RTRIM(COLOUR)) = 'FMCKTX7'
AND MOVEMENT IS NULL
AND TYPE  IS NULL
AND LTRIM(RTRIM(TAGNO)) <> 2137674
ORDER BY CDATE DESC

---- SE CREA LA TABLA CON PIELES CON MOVIMIENTO EN NULL
--INSERT INTO RP_SC_PIEL_MOVEMENT_NULL( 
--		[CDATE],[COLOUR],[LOT],[HIDE],[SQF],[TAGNO],[YARDAS],[YLB],[PESO],[TYPE],[MOVEMENT],[K_CLASIFICACION]
--		)
-- SELECT CDATE,[COLOUR],[LOT],[HIDE],[SQF],[TAGNO],[YARDAS],[YLB],[PESO],[TYPE],[MOVEMENT],[K_CLASIFICACION]
-- FROM RP_SC   
-- WHERE  LTRIM(RTRIM(COLOUR)) = 'FMCKTX7'
--AND MOVEMENT IS NULL
--AND TYPE  IS NULL
--AND LTRIM(RTRIM(TAGNO)) <> 2137674

---- SE VERIFICA QUE EL RESULTADO SEA EL MISMO DE LA TABLA RESPALDO
--SELECT * FROM RP_SC_PIEL_MOVEMENT_NULL
--WHERE  LTRIM(RTRIM(COLOUR)) = 'FMCKTX7'
--AND MOVEMENT IS NULL
--AND TYPE  IS NULL
--AND ID IN (SELECT ID RP_SC)

---- SE BORRAN LAS PIELES CON MOVIMIENTO EN NULL DE LA RP_SC
--DELETE RP_SC  
-- WHERE  LTRIM(RTRIM(COLOUR)) = 'FMCKTX7'
--AND MOVEMENT IS NULL
--AND TYPE  IS NULL
--AND LTRIM(RTRIM(TAGNO)) <> 2137674
--/////////////////////////////////////////////////////////////////

---- PIELES CON FOLIOS EN STATUS XX
SELECT * FROM RP_Folios WHERE TAG IN (3787545,3787582)

SELECT DISTINCT  RP_SC.* FROM RP_SC
INNER JOIN RP_Folios ON LTRIM(RTRIM(RP_SC.TAGNO)) = LTRIM(RTRIM(RP_Folios.TAG))
WHERE	LTRIM(RTRIM(COLOUR)) = 'FMCKTX7'
AND		LTRIM(RTRIM(STATUS)) = 'XX'
AND		LTRIM(RTRIM(TYPE)) NOT IN ('2')
AND		LTRIM(RTRIM(TAGNO)) <> 2137674
--AND LTRIM(RTRIM(TAGNO)) IN (SELECT LTRIM(RTRIM(TAG))  FROM RP_Folios WHERE LTRIM(RTRIM(STATUS)) = 'XX')

---- SE CREA LA TABLA CON PIELES CON FOLIOS STATUS XX
 SELECT * FROM RP_SC_FOLIO_STATUS_XX
--SELECT DISTINCT RP_SC.* INTO RP_SC_FOLIO_STATUS_XX
--FROM RP_SC
--INNER JOIN RP_Folios ON LTRIM(RTRIM(RP_SC.TAGNO)) = LTRIM(RTRIM(RP_Folios.TAG))
--WHERE	LTRIM(RTRIM(COLOUR)) = 'FMCKTX7'
--AND		LTRIM(RTRIM(STATUS)) = 'XX'
--AND		LTRIM(RTRIM(TYPE)) NOT IN ('2')
--AND		LTRIM(RTRIM(TAGNO)) <> 2137674

---- SE VERIFICA QUE EL RESULTADO SEA EL MISMO DE LA TABLA RP_SC_FOLIO_STATUS_XX
SELECT * FROM RP_SC
WHERE	LTRIM(RTRIM(COLOUR)) = 'FMCKTX7'
AND		LTRIM(RTRIM(TYPE)) NOT IN ('2')
AND		LTRIM(RTRIM(TAGNO)) <> 2137674
AND		ID IN (SELECT DISTINCT ID FROM RP_SC_FOLIO_STATUS_XX)

SELECT * FROM RP_SC_FOLIO_STATUS_XX
INNER JOIN RP_Folios ON LTRIM(RTRIM(RP_SC.TAGNO)) = LTRIM(RTRIM(RP_Folios.TAG))
WHERE	LTRIM(RTRIM(COLOUR)) = 'FMCKTX7'
AND		LTRIM(RTRIM(STATUS)) = 'XX'
AND		LTRIM(RTRIM(TYPE)) NOT IN ('2')
AND		LTRIM(RTRIM(TAGNO)) <> 2137674


--/////////////////////////////////////////////////////////////////
-- ORDENES TERMINADAS CON FOLIOS SIN STATUS XX
SELECT * FROM CCJOBHDR_SQL WHERE LTRIM(RTRIM([status])) = 'C' AND LTRIM(RTRIM(COLOUR)) = 'MCKTX7'
AND LTRIM(RTRIM(JOBNO)) IN (SELECT LTRIM(RTRIM(JOBNO)) FROM RP_Folios WHERE LTRIM(RTRIM(STATUS)) <> 'XX'	)
--AND datecreated > 20200301
ORDER BY datecreated DESC

 SELECT * FROM RP_Folios
 INNER JOIN CCJOBHDR_SQL ON  LTRIM(RTRIM(RP_Folios.JOBNO)) = LTRIM(RTRIM(CCJOBHDR_SQL.JOBNO))
  WHERE   LTRIM(RTRIM(CCJOBHDR_SQL.[status])) = 'C' AND LTRIM(RTRIM(COLOUR)) = 'MCKTX7' 
AND RP_Folios.[status] <> 'XX'
--ORDER BY datecreated DESC

 SELECT * FROM RP_Folios WHERE  LTRIM(RTRIM(JOBNO)) IN (
			SELECT LTRIM(RTRIM(jobno)) FROM CCJOBHDR_SQL 
			WHERE LTRIM(RTRIM([status])) = 'C' AND LTRIM(RTRIM(COLOUR)) = 'MCKTX7' 	)
AND STATUS <> 'XX'
--ORDER BY TAG DESC



--UPDATE RP_Folios
--	SET STATUS = 'XX'
--WHERE  LTRIM(RTRIM(JOBNO)) IN (
--			SELECT LTRIM(RTRIM(jobno)) FROM CCJOBHDR_SQL 
--			WHERE LTRIM(RTRIM([status])) = 'C' AND LTRIM(RTRIM(COLOUR)) = 'MCKTX7' 	)
--AND STATUS <> 'XX'

--INSERT INTO RP_SC_FOLIO_STATUS_XX( 
--       [CDATE],[COLOUR],[LOT],[HIDE],[SQF],[TAGNO],[YARDAS],[YLB],[PESO],[TYPE],[MOVEMENT],[K_CLASIFICACION]
--              )
--SELECT CDATE,[COLOUR],[LOT],[HIDE],[SQF],[TAGNO],[YARDAS],[YLB],[PESO],[TYPE],[MOVEMENT],[K_CLASIFICACION]
--FROM RP_SC 


--SELECT DISTINCT RP_SC.* --INTO RP_SC_FOLIO_STATUS_XX
--FROM RP_SC
--INNER JOIN RP_Folios ON LTRIM(RTRIM(RP_SC.TAGNO)) = LTRIM(RTRIM(RP_Folios.TAG))
--WHERE	LTRIM(RTRIM(COLOUR)) = 'FMCKTX7'
--AND		LTRIM(RTRIM(STATUS)) = 'XX'
--AND		LTRIM(RTRIM(TYPE)) NOT IN ('2')
--AND		LTRIM(RTRIM(TAGNO)) <> 2137674
--ORDER BY CDATE DESC

--DELETE RP_SC
--WHERE	LTRIM(RTRIM(COLOUR)) = 'FMCKTX7'
--AND		LTRIM(RTRIM(TYPE)) NOT IN ('2')
--AND		LTRIM(RTRIM(TAGNO)) <> 2137674
--AND ID IN (SELECT ID FROM RP_SC_FOLIO_STATUS_XX2)


--/////////////////////////////////////////////////////////////////
-- PIELES DUPLICADAS

SELECT  LOT, HIDE,count(*) FROM RP_SC 
WHERE  LTRIM(RTRIM(COLOUR)) = 'FMCKTX7'
--AND LTRIM(RTRIM(TYPE)) NOT IN ('2')
GROUP BY  LOT, HIDE 
HAVING COUNT(*)>1
--================================================================

DECLARE @TBL_PIEL_DUPLICADA TABLE(
	LOTE	VARCHAR(10),
	PIEL	VARCHAR(5)
	)

INSERT INTO @TBL_PIEL_DUPLICADA
		SELECT  LTRIM(RTRIM(LOT)), LTRIM(RTRIM(HIDE))
		FROM	RP_SC 
		WHERE	LTRIM(RTRIM(COLOUR)) = 'FMCKTX7' 
		--AND LTRIM(RTRIM(TYPE)) NOT IN ('2')
		GROUP BY  LTRIM(RTRIM(LOT)), LTRIM(RTRIM(HIDE)) 
		HAVING COUNT(*)>1


SELECT  RP_SC.* 
FROM RP_SC
INNER JOIN @TBL_PIEL_DUPLICADA AS TBL_PIEL_DUP 
			ON	LTRIM(RTRIM(RP_SC.LOT)) = TBL_PIEL_DUP.LOTE 
				AND LTRIM(RTRIM(RP_SC.HIDE)) = TBL_PIEL_DUP.PIEL
				AND LTRIM(RTRIM(COLOUR)) = 'FMCKTX7' 
				--AND LTRIM(RTRIM(TYPE)) NOT IN ('2')
ORDER BY LOTE DESC

 --/////////////////////////////////////////////////////////////////

 
SELECT D_TIPO_PIEL_LOG,usuario,
PIEL_LOG.*  
FROM PIEL_LOG 
INNER JOIN users_pearl ON PIEL_LOG.K_USUARIO_ALTA = users_pearl.codigo
INNER JOIN TIPO_PIEL_LOG ON PIEL_LOG.K_TIPO_PIEL_LOG=TIPO_PIEL_LOG.K_TIPO_PIEL_LOG
WHERE  --ORDEN_ORIGEN = 11247
LOTE = 32691 AND PIEL IN ( 0161)

SELECT * FROM RP_Folios 
WHERE LTRIM(RTRIM(TAG))  IN (3787718)


SELECT * FROM CCJOBHDR_SQL WHERE  LTRIM(RTRIM(jobno)) IN ('11049 ' )



select * from HIDESHDR_SQL   
 inner join HIDESLIN_SQL on  HIDESLIN_SQL.FILENO = HIDESHDR_SQL.FILENO
AND	LTRIM(RTRIM(PLOT)) = '104882' 
 AND LTRIM(RTRIM(HIDE)) IN   ('0281')
 
SELECT  * FROM cccuthst_sql 
WHERE --LTRIM(RTRIM(COLOUR)) = 'FMCKTX7'  
--AND	
LTRIM(RTRIM(lotno)) = '032681' 
 AND LTRIM(RTRIM(hideno))   IN ('0183')
ORDER BY HIDENO ASC
 --================================================================
  
  SELECT  * FROM RP_SC_FOLIO_STATUS_XX
 WHERE	LTRIM(RTRIM(COLOUR)) = 'FMCKTX7' 
AND	LTRIM(RTRIM(LOT)) = '32681' 
 AND LTRIM(RTRIM(HIDE)) IN   ('0183')

SELECT  * FROM RP_SC
WHERE	LTRIM(RTRIM(COLOUR)) = 'FMCKTX7' 
AND	LTRIM(RTRIM(LOT)) = '32681' 
 AND LTRIM(RTRIM(HIDE)) IN   ('0183')

 --INSERT INTO RP_SC_HIDE_DELETE( 
	--	[CDATE],[COLOUR],[LOT],[HIDE],[SQF],[TAGNO],[YARDAS],[YLB],[PESO],[TYPE],[MOVEMENT],[K_CLASIFICACION]
	--	)
 --SELECT [CDATE],[COLOUR],[LOT],[HIDE],[SQF],[TAGNO],[YARDAS],[YLB],[PESO],[TYPE],[MOVEMENT],[K_CLASIFICACION]
 --FROM RP_SC
 --WHERE  (SQF = '0' OR SQF = '0.00')
-- WHERE	LTRIM(RTRIM(COLOUR)) = 'FMCKTX7' 
--AND	LTRIM(RTRIM(LOT)) = '32691' 
--AND LTRIM(RTRIM(HIDE)) IN   ('0161')
--AND TAGNO = 3786953
--AND ID = 4587588


 --================================================================

 SELECT * FROM	RP_SC_HIDE_DELETE
  WHERE  (SQF = '0' OR SQF = '0.00')
-- WHERE LTRIM(RTRIM(COLOUR)) = 'FMCKTX7' 
--AND	LTRIM(RTRIM(LOT)) = '33002' 
--AND LTRIM(RTRIM(HIDE)) IN   ('1033')

  
-- --================================================================

 --DELETE  FROM RP_SC
 -- WHERE  (SQF = '0' OR SQF = '0.00')
-- WHERE LTRIM(RTRIM(COLOUR)) = 'FMCKTX7' 
--AND	LTRIM(RTRIM(LOT)) = '33002' 
--AND LTRIM(RTRIM(HIDE)) IN   ('1033')
--AND ID = 4587588


  --///////////////////////////////////////////////////////////////// 

  --SELECT DISTINCT LTRIM(RTRIM(TAGNO)) FROM RP_SC

  --SELECT * FROM RP_FOLIOS WHERE STATUS = 'A' AND LTRIM(RTRIM(TAG))  NOT IN (SELECT LTRIM(RTRIM(TAGNO)) FROM RP_SC WHERE TAGNO <> 0)

