

/*

INSERT INTO COLORES_CONTROLADOS ( COLOR)
SELECT 'FWLCPX7'

INSERT INTO RP_SC_PIEL_MOVEMENT_NULL( 
		[CDATE],[COLOUR],[LOT],[HIDE],[SQF],[TAGNO],[YARDAS],[YLB],[PESO],[TYPE],[MOVEMENT],[K_CLASIFICACION]
		)
SELECT [CDATE],[COLOUR],[LOT],[HIDE],[SQF],[TAGNO],[YARDAS],[YLB],[PESO],[TYPE],[MOVEMENT],[K_CLASIFICACION]
FROM RP_SC WHERE LTRIM(RTRIM(COLOUR)) IN (SELECT COLOR FROM [DATA_02].DBO.COLORES_CONTROLADOS WHERE COLOR IN 'FMCKSTT')
AND MOVEMENT IS NULL

*/


SELECT * FROM COLORES_CONTROLADOS WHERE COLOR IN('FNPJTX7','FNPJSA5','FMCKSA5')

SELECT * FROM RP_SC WHERE COLOUR = '' AND  MOVEMENT IS NULL

SELECT DISTINCT COLOUR FROM RP_SC_FOLIO_TYPE_2 WHERE TAGNO = 3787973 


SELECT * FROM RP_SC_FOLIO_TYPE_2 WHERE TAGNO = 3787973 AND COLOUR = 'FCPATX7'

SELECT * FROM RP_SC_FOLIO_TYPE_2 WHERE TAGNO = 3787973 AND COLOUR = 'FWSPAX7'


SELECT * FROM RP_SC WHERE HIDE = '0023' AND LOT = '401151'

SELECT * FROM RP_SC_TEMP WHERE HIDE = '0023' AND LOT = '401151'

SELECT * FROM RP_Folios WHERE TAG = 3785738


SELECT * FROM PIEL_LOG WHERE PIEL = 30 AND LOTE = 401211

SELECT * FROM TIPO_PIEL_LOG 

