	
	DECLARE @TBL_PIELES_DUPPLICADAS_FINAL TABLE(
	ID			INT IDENTITY(1,1),
	[COLOUR]	VARCHAR(20),
	[LOT]		VARCHAR(20),
	[HIDE]		VARCHAR(20),
	[SQF]		VARCHAR(20),
	[TAGNO]		INT,
	[TYPE]		VARCHAR(20),
	[MOVEMENT] VARCHAR(20)
	)

	---- cargar pieles de los folios asignados a mesa
	INSERT INTO @TBL_PIELES_DUPPLICADAS_FINAL
	SELECT [COLOUR], [LOT], [HIDE], [SQF], [TAGNO], [TYPE], [MOVEMENT] 
	FROM RP_SC_HIDE_DELETE (NOLOCK)
	WHERE LTRIM(RTRIM(COLOUR)) = 'FNRUDX9' 
	AND TAGNO IN ( SELECT FOLIO FROM CCJOBHDR_SQL WHERE COLOUR = 'NRUDX9' AND STATUS = 'P' AND folio IS NOT NULL )
	ORDER BY LOT, HIDE

	---- cargar pieles a un solo folio las pieles de MQU
	INSERT INTO @TBL_PIELES_DUPPLICADAS_FINAL
	SELECT [COLOUR], [LOT], [HIDE], [SQF], 3800672, 'C', 'MQU'
	FROM RP_SC_FOLIO_TYPE_2 
	WHERE LTRIM(RTRIM(COLOUR)) = 'FNRUDX9' 
	AND TAGNO IN ( 3790344, 3790354 )
	ORDER BY LOT, HIDE

	---- cargar pieles a un solo folio BASE las pieles de MHI
	INSERT INTO @TBL_PIELES_DUPPLICADAS_FINAL
	SELECT [COLOUR], [LOT], [HIDE], [SQF], 3461874, 'C', 'MHI'
	FROM RP_SC_FOLIO_TYPE_2 
	WHERE LTRIM(RTRIM(COLOUR)) = 'FNRUDX9' 
	AND TAGNO IN ( 3790415 )
	ORDER BY LOT, HIDE

	---- cargar pieles de los folios asignados a mesa
	INSERT INTO @TBL_PIELES_DUPPLICADAS_FINAL
	SELECT [COLOUR], [LOT], [HIDE], [SQF], 3461874, [TYPE], [MOVEMENT] 
	FROM RP_SC_HIDE_DELETE (NOLOCK)
	WHERE LTRIM(RTRIM(COLOUR)) = 'FNRUDX9'  AND LOT = '68171' AND HIDE IN (SELECT HIDE FROM HIDESLIN_SQL	WHERE FILENO IN (	'210726133957T1000001', '210728113444T1000001', '210728121225T1000001') )
	ORDER BY LOT, HIDE
	
	DECLARE @VP_FOLIO INT = 0
	DECLARE @VP_COLOR VARCHAR(20) = ''
	DECLARE @VP_LOTE VARCHAR(20) = ''
	DECLARE @VP_HIDE VARCHAR(10) = ''
	DECLARE @VP_SQF VARCHAR(10) = ''
	DECLARE @VP_LOCACION VARCHAR(10) = ''

	DECLARE CU_PIELES_DUPLICADAS CURSOR 
	FOR SELECT TAGNO, LTRIM(RTRIM(COLOUR)), LTRIM(RTRIM(LOT)), LTRIM(RTRIM(HIDE)), LTRIM(RTRIM(SQF)), LTRIM(RTRIM(MOVEMENT))
		FROM @TBL_PIELES_DUPPLICADAS_FINAL 
		WHERE LTRIM(RTRIM(COLOUR)) = 'FNRUDX9' 
		ORDER BY ID ASC
	
	OPEN CU_PIELES_DUPLICADAS
	FETCH NEXT FROM CU_PIELES_DUPLICADAS INTO @VP_FOLIO, @VP_COLOR, @VP_LOTE, @VP_HIDE, @VP_SQF, @VP_LOCACION
	
	WHILE @@FETCH_STATUS = 0
		BEGIN	
			IF (SELECT COUNT(ID) FROM RP_SC (NOLOCK) WHERE COLOUR = @VP_COLOR AND LOT = @VP_LOTE AND HIDE = @VP_HIDE ) = 0
				BEGIN
					--INSERT INTO RP_SC( 
					--					[CDATE],[COLOUR],[LOT],[HIDE],[SQF],[TAGNO],[YARDAS],[YLB],[PESO],[TYPE],[MOVEMENT],[K_CLASIFICACION]
					--				)
					--			VALUES( GETDATE(), @VP_COLOR, @VP_LOTE, @VP_HIDE, @VP_SQF, @VP_FOLIO, NULL, NULL, NULL, 'C', @VP_LOCACION, 0
					--					)								
				END
			FETCH NEXT FROM CU_PIELES_DUPLICADAS INTO @VP_FOLIO, @VP_COLOR, @VP_LOTE, @VP_HIDE, @VP_SQF, @VP_LOCACION
		END
	CLOSE CU_PIELES_DUPLICADAS
	DEALLOCATE CU_PIELES_DUPLICADAS
	
		SELECT * FROM  CCJOBHDR_SQL WHERE LTRIM(RTRIM(COLOUR)) = 'NRUDX9' AND STATUS = 'P' AND FOLIO IS NOT NULL ORDER BY MACHINE

	SELECT  *
	FROM RP_SC
	WHERE LTRIM(RTRIM(COLOUR)) = 'FNRUDX9' 
	ORDER BY MOVEMENT

	------ SACAR DUPLICADOS FOLIOS EN PRD
	--SELECT  LOT, HIDE, COUNT(*) 
	--FROM RP_SC
	--WHERE LTRIM(RTRIM(COLOUR)) = 'FNRUDX9' 
	--AND TAGNO IN (SELECT FOLIO FROM  CCJOBHDR_SQL WHERE LTRIM(RTRIM(COLOUR)) = 'NRUDX9' AND STATUS = 'P' AND FOLIO IS NOT NULL)
	--GROUP BY  LOT, HIDE 
	--HAVING COUNT(*)>1
	--ORDER BY LOT, HIDE
   
	-- SACAR  PIELES DUPLICADAS
	SELECT  LOT, HIDE, COUNT(*) AS N_DUPLICADA
	FROM RP_SC (NOLOCK)
	WHERE LTRIM(RTRIM(COLOUR)) = 'FNRUDX9' 
	GROUP BY  LOT, HIDE 
	HAVING COUNT(*)>1
	ORDER BY LOT, HIDE

	-- PIES CUADRADOS POR LOTE EN MHI
	SELECT  LOT, COUNT(HIDE) AS 'PIELS', SUM(CONVERT(DECIMAL(13,2),LTRIM(RTRIM(SQF)))) AS SQF
	FROM RP_SC (NOLOCK)
	WHERE LTRIM(RTRIM(COLOUR)) = 'FNRUDX9' 
	AND MOVEMENT = 'MHI'
	GROUP BY  LOT
	ORDER BY LOT 

	-- PIES CUADRADOS POR LOTE EN MHI
	SELECT  LOT, COUNT(HIDE) AS 'PIELS', SUM(CONVERT(DECIMAL(13,2),LTRIM(RTRIM(SQF)))) AS SQF
	FROM RP_SC (NOLOCK)
	WHERE LTRIM(RTRIM(COLOUR)) = 'FNRUDX9' 
	AND MOVEMENT = 'MQU'
	GROUP BY  LOT
	ORDER BY LOT 
