	
	DECLARE @TBL_PIELES_DUPPLICADAS_FINAL TABLE(
	ID			INT IDENTITY(1,1),
	[COLOUR]	VARCHAR(20),
	[LOT]		VARCHAR(20),
	[HIDE]		VARCHAR(20),
	[SQF]		VARCHAR(20),
	[TAGNO]		INT,
	[TYPE]		VARCHAR(20),
	[MOVEMENT] VARCHAR(20)
	)
	
	-- cargar pieles al folio base las pieles de LOS DETALLADOS
	--INSERT INTO @TBL_PIELES_DUPPLICADAS_FINAL
	--SELECT [COLOUR], [LOT], [HIDE], [SQF], TAGNO, TYPE, MOVEMENT
	--FROM RP_SC (NOLOCK)
	--WHERE LTRIM(RTRIM(COLOUR)) = 'FCNPDX9' 
	--ORDER BY LOT, HIDE

	---- cargar pieles de los folios asignados a mesa
	--INSERT INTO @TBL_PIELES_DUPPLICADAS_FINAL
	--SELECT [COLOUR], [LOT], [HIDE], [SQF], [TAGNO], [TYPE], [MOVEMENT] 
	--FROM RP_SC_HIDE_DELETE (NOLOCK)
	--WHERE LTRIM(RTRIM(COLOUR)) = 'FCNPDX9' 
	--AND TAGNO IN (SELECT FOLIO FROM CCJOBHDR_SQL WHERE COLOUR = 'CNPDX9' AND STATUS = 'P' AND folio IS NOT NULL )
	--ORDER BY LOT, HIDE

	---- cargar pieles a un solo folio las pieles de MQU
	INSERT INTO @TBL_PIELES_DUPPLICADAS_FINAL
	SELECT [COLOUR], [LOT], [HIDE], [SQF], 3793164, 'C', 'MQU'
	FROM RP_SC_FOLIO_TYPE_2 
	WHERE LTRIM(RTRIM(COLOUR)) = 'FCNPDX9' 
	AND TAGNO IN ( 3790344, 3790354 )
	ORDER BY LOT, HIDE
	
	DECLARE @VP_FOLIO INT = 0
	DECLARE @VP_COLOR VARCHAR(20) = ''
	DECLARE @VP_LOTE VARCHAR(20) = ''
	DECLARE @VP_HIDE VARCHAR(10) = ''
	DECLARE @VP_SQF VARCHAR(10) = ''
	DECLARE @VP_LOCACION VARCHAR(10) = ''

	DECLARE CU_PIELES_DUPLICADAS CURSOR 
	FOR SELECT TAGNO, LTRIM(RTRIM(COLOUR)), LTRIM(RTRIM(LOT)), LTRIM(RTRIM(HIDE)), LTRIM(RTRIM(SQF)), LTRIM(RTRIM(MOVEMENT))
		FROM @TBL_PIELES_DUPPLICADAS_FINAL 
		WHERE LTRIM(RTRIM(COLOUR)) = 'FCNPDX9' 
		ORDER BY ID ASC
	
	OPEN CU_PIELES_DUPLICADAS
	FETCH NEXT FROM CU_PIELES_DUPLICADAS INTO @VP_FOLIO, @VP_COLOR, @VP_LOTE, @VP_HIDE, @VP_SQF, @VP_LOCACION
	
	WHILE @@FETCH_STATUS = 0
		BEGIN	
			IF (SELECT COUNT(ID) FROM RP_SC (NOLOCK) WHERE COLOUR = @VP_COLOR AND LOT = @VP_LOTE AND HIDE = @VP_HIDE ) = 0
				BEGIN
					--INSERT INTO RP_SC( 
					--					[CDATE],[COLOUR],[LOT],[HIDE],[SQF],[TAGNO],[YARDAS],[YLB],[PESO],[TYPE],[MOVEMENT],[K_CLASIFICACION]
					--				)
					--			VALUES( GETDATE(), @VP_COLOR, @VP_LOTE, @VP_HIDE, @VP_SQF, @VP_FOLIO, NULL, NULL, NULL, 'C', @VP_LOCACION, 0
					--					)								
				END
			FETCH NEXT FROM CU_PIELES_DUPLICADAS INTO @VP_FOLIO, @VP_COLOR, @VP_LOTE, @VP_HIDE, @VP_SQF, @VP_LOCACION
		END
	CLOSE CU_PIELES_DUPLICADAS
	DEALLOCATE CU_PIELES_DUPLICADAS
	
	--	SELECT * FROM  CCJOBHDR_SQL WHERE LTRIM(RTRIM(COLOUR)) = 'NRUDX9' AND STATUS = 'P' AND FOLIO IS NOT NULL ORDER BY MACHINE

	--SELECT * FROM RP_SC WHERE LTRIM(RTRIM(COLOUR)) = 'FNRUDX9' 
	--AND TAGNO IN (SELECT FOLIO FROM  CCJOBHDR_SQL WHERE LTRIM(RTRIM(COLOUR)) = 'NRUDX9' AND STATUS = 'P' AND FOLIO IS NOT NULL)

	---- SACAR DUPLICADOS FOLIOS EN PRD
	--SELECT  LOT, HIDE, COUNT(*) 
	--FROM RP_SC
	--WHERE LTRIM(RTRIM(COLOUR)) = 'FNRUDX9' 
	--AND TAGNO IN (SELECT FOLIO FROM  CCJOBHDR_SQL WHERE LTRIM(RTRIM(COLOUR)) = 'NRUDX9' AND STATUS = 'P' AND FOLIO IS NOT NULL)
	--GROUP BY  LOT, HIDE 
	--HAVING COUNT(*)>1
	--ORDER BY LOT, HIDE
	
--	SELECT  LOT, COUNT(HIDE) AS 'PIELS', SUM(CONVERT(DECIMAL(13,2),LTRIM(RTRIM(SQF)))) AS SQF
--FROM RP_SC_FOLIO_TYPE_2 
--WHERE LTRIM(RTRIM(COLOUR)) = 'FCNPDX9' 
--AND TAGNO IN (3790368, 3790402, 3790403)
--GROUP BY  LOT
--	ORDER BY LOT 
   
    -- 3312
	--SELECT COUNT(ID) FROM 	RP_SC
	--WHERE LTRIM(RTRIM(COLOUR)) = 'FCNPDX9' 
	--AND MOVEMENT = 'MHI'

	-- SACAR  PIELES DUPLICADAS
	SELECT  LOT, HIDE, COUNT(*) AS N_DUPLICADA
	FROM RP_SC (NOLOCK)
	WHERE LTRIM(RTRIM(COLOUR)) = 'FCNPDX9' 
	GROUP BY  LOT, HIDE 
	HAVING COUNT(*)>1
	ORDER BY LOT, HIDE

	-- PIES CUADRADOS POR LOTE EN MHI
	SELECT  LOT, COUNT(HIDE) AS 'PIELS', SUM(CONVERT(DECIMAL(13,2),LTRIM(RTRIM(SQF)))) AS SQF
	FROM RP_SC (NOLOCK)
	WHERE LTRIM(RTRIM(COLOUR)) = 'FCNPDX9' 
	AND MOVEMENT = 'MQU'
	GROUP BY  LOT
	ORDER BY LOT 

	-- PIES CUADRADOS POR LOTE EN MQU
	--SELECT  LOT, SUM(CONVERT(DECIMAL(13,2),LTRIM(RTRIM(SQF)))) AS SQF
	--FROM RP_SC
	--WHERE LTRIM(RTRIM(COLOUR)) = 'FCPRHL1' 
	--AND MOVEMENT = 'MQU'
	--GROUP BY  LOT
	--ORDER BY LOT 

	-- PIES CUADRADOS POR LOTE EN MESAS
	--SELECT  LOT, SUM(CONVERT(DECIMAL(13,2),LTRIM(RTRIM(SQF)))) AS SQF
	--FROM RP_SC
	--WHERE LTRIM(RTRIM(COLOUR)) = 'FCPRHL1' 
	--AND MOVEMENT = 'T13'
	--GROUP BY  LOT
	--ORDER BY LOT 

	--SELECT  LOT, SUM(CONVERT(DECIMAL(13,2),LTRIM(RTRIM(SQF)))) AS SQF
	--FROM RP_SC
	--WHERE LTRIM(RTRIM(COLOUR)) = 'FCPRHL1' 
	--AND MOVEMENT = 'T68'
	--GROUP BY  LOT
	--ORDER BY LOT 

	--SELECT  LOT, SUM(CONVERT(DECIMAL(13,2),LTRIM(RTRIM(SQF)))) AS SQF
	--FROM RP_SC
	--WHERE LTRIM(RTRIM(COLOUR)) = 'FCPRHL1' 
	--AND MOVEMENT = 'T71'
	--GROUP BY  LOT
	--ORDER BY LOT 

	
--SELECT * FROM CCJOBHDR_SQL WHERE COLOUR = 'CPRHL1' AND STATUS = 'P' and folio is not null

	--SELECT LOT, SUM(CONVERT(DECIMAL(13,2),LTRIM(RTRIM(SQF)))) AS SQF FROM RP_SC WHERE TAGNO = 3825608 
	--GROUP BY  LOT 
	--ORDER BY LOT

	--SELECT * FROM RP_SC WHERE TAGNO = 3825608 ORDER BY HIDE
	--SELECT * FROM RP_Folios WHERE TAG IN (3815708, 3825608)
	--SELECT * FROM CCJOBHDR_SQL WHERE FOLIO = 3825608
	--SELECT * FROM CCJOBHDR_SQL WHERE COLOUR = 'CPRHL1' AND STATUS = 'P' and folio is not null
	--ORDER BY machine

	--SELECT * FROM RP_SC WHERE TAGNO = 3835902 ORDER BY lot, HIDE	
	
	--SELECT * FROM cccuthst_sql WHERE jobno = '33696' ORDER BY lotno, hideno