	DECLARE @TBL_PIELES_DUPPLICADAS_FINAL TABLE(
	ID			INT,
	[COLOUR]	VARCHAR(20),
	[LOT]		VARCHAR(20),
	[HIDE]		VARCHAR(20),
	[SQF]		VARCHAR(20),
	[TAGNO]		INT,
	[TYPE]		VARCHAR(20),
	[MOVEMENT] VARCHAR(20)
	)

	DECLARE @TBL_PIELES_DUPLICADAS TABLE(
		LOT VARCHAR(20),
		HIDE VARCHAR(10)
	)
	
	INSERT INTO @TBL_PIELES_DUPLICADAS
	SELECT  LOT, HIDE
	FROM RP_SC
	WHERE COLOUR = 'FNRUML8' 
	
	INSERT INTO @TBL_PIELES_DUPLICADAS
	SELECT LOT, HIDE FROM RP_SC_FOLIO_TYPE_2 
	WHERE COLOUR = 'FNRUML8' 
	AND TAGNO IN ( 3789947, 3789949 )
	
	--DECLARE @VP_LOTE VARCHAR(20) = ''
	--DECLARE @VP_HIDE VARCHAR(10) = ''
	--DECLARE @VP_N_HIDE INT = 0

	--DECLARE CU_PIELES_DUPLICADAS CURSOR 
	--FOR SELECT  LOT, HIDE, COUNT(*) 
	--		FROM @TBL_PIELES_DUPLICADAS
	--		GROUP BY  LOT, HIDE 
	--		HAVING COUNT(*)>1
	--		ORDER BY LOT, HIDE
	
	--OPEN CU_PIELES_DUPLICADAS
	--FETCH NEXT FROM CU_PIELES_DUPLICADAS INTO @VP_LOTE, @VP_HIDE, @VP_N_HIDE
	
	--WHILE @@FETCH_STATUS = 0
	--	BEGIN		
	--		INSERT INTO @TBL_PIELES_DUPPLICADAS_FINAL
	--		SELECT ID, [COLOUR], [LOT], [HIDE], [SQF], [TAGNO], [TYPE], [MOVEMENT]
	--		FROM RP_SC
	--		WHERE COLOUR = 'FNRUML8' 
	--		AND LOT = @VP_LOTE
	--		AND HIDE = @VP_HIDE

	--		INSERT INTO @TBL_PIELES_DUPPLICADAS_FINAL
	--		SELECT ID, [COLOUR], [LOT], [HIDE], [SQF], [TAGNO], [TYPE], [MOVEMENT] 
	--		FROM RP_SC_FOLIO_TYPE_2 
	--		WHERE COLOUR = 'FNRUML8' 
	--		AND TAGNO IN ( 3789947, 3789949 )
	--		AND LOT = @VP_LOTE
	--		AND HIDE = @VP_HIDE
	
	--		DELETE RP_SC_FOLIO_TYPE_2 
	--		WHERE COLOUR = 'FNRUML8' 
	--		AND TAGNO IN ( 3789947, 3789949 )
	--		AND LOT = @VP_LOTE
	--		AND HIDE = @VP_HIDE

	--		FETCH NEXT FROM CU_PIELES_DUPLICADAS INTO @VP_LOTE, @VP_HIDE, @VP_N_HIDE
	--	END
	--CLOSE CU_PIELES_DUPLICADAS
	--DEALLOCATE CU_PIELES_DUPLICADAS

	SELECT  LOT, HIDE, COUNT(*) 
	FROM @TBL_PIELES_DUPLICADAS
	GROUP BY  LOT, HIDE 
	HAVING COUNT(*)>1
	ORDER BY LOT, HIDE

	--SELECT * FROM @TBL_PIELES_DUPPLICADAS_FINAL ORDER BY LOT, HIDE

--SELECT * FROM RP_SC
--WHERE COLOUR = 'FNRUML8' 
--AND LOT = '64521'
--AND HIDE = '0020'

SELECT  LOT, HIDE, COUNT(*) 
	FROM RP_SC_FOLIO_TYPE_2
	WHERE COLOUR = 'FNRUML8' 
	AND TAGNO IN ( 3789947, 3789949 )
	GROUP BY  LOT, HIDE 
	HAVING COUNT(*)>1
	ORDER BY LOT, HIDE

--SELECT * FROM RP_SC_FOLIO_TYPE_2 
--WHERE COLOUR = 'FNRUML8' 
--AND TAGNO IN ( 3789947, 3789949 )
--AND LOT = '64521'
--AND HIDE = '0020'