
INSERT INTO RP_SC( 
		[CDATE],[COLOUR],[LOT],[HIDE],[SQF],[TAGNO],[TYPE],MOVEMENT
		)
SELECT F_LOG, COLOR, LOTE, RIGHT('0000' + CONVERT(VARCHAR(4), PIEL), 4), CONVERT(DECIMAL(13,2), SQF), 3807852, 'C', LOCACION_DESTINO
FROM PIEL_LOG 
INNER JOIN users_pearl ON PIEL_LOG.K_USUARIO_ALTA = users_pearl.codigo
INNER JOIN TIPO_PIEL_LOG ON PIEL_LOG.K_TIPO_PIEL_LOG = TIPO_PIEL_LOG.K_TIPO_PIEL_LOG
WHERE
LOTE IN (34062)              
AND PIEL IN (553, 552)
AND PIEL_LOG.K_TIPO_PIEL_LOG IN (4)
ORDER BY K_PIEL_LOG DESC