
--INSERT INTO RP_SC( 
--		[CDATE],[COLOUR],[LOT],[HIDE],[SQF],[TAGNO],[TYPE],MOVEMENT
--		)
--SELECT F_LOG, COLOR, LOTE, RIGHT('0000' + CONVERT(VARCHAR(4), PIEL), 4), CONVERT(DECIMAL(13,2), SQF), FOLIO_DESTINO, 'C', LOCACION_DESTINO
--FROM PIEL_LOG 
--WHERE LOTE IN (106771)    
--AND  PIEL   IN (135, 124, 132, 131)
--AND PIEL_LOG.K_TIPO_PIEL_LOG IN (5)