
--	USE DATA_02


/*
-- PIEL AGREGADA MANUALMENTE
--INSERT INTO RP_SC( [CDATE],[COLOUR],[LOT],[HIDE],[SQF],[TAGNO],[YARDAS],[YLB],[PESO],[TYPE],[MOVEMENT],[K_CLASIFICACION]
--		)
-- SELECT GETDATE(),'FMCKTX7','32271', '9998','39.70','2137674',NULL,NULL,NULL,'C','MHI',0
 */

SELECT * FROM  RP_SC_TEMP WHERE TAGNO IN (3793845 )

SELECT * FROM  RP_SC WHERE TAGNO IN (3798698 )
 
 SELECT * FROM  RP_Folios WHERE TAG = (3793845) 

SELECT * FROM ccjobhdr_sql WHERE jobno = '18010'

SELECT * FROM RP_SC_PRT

SELECT	* --qty_on_hand
FROM	IMLSMST_SQL
WHERE	LTRIM(RTRIM(LOC))='MHI'
AND		LTRIM(RTRIM(ITEM_NO))='FMCKTX7'
AND		LTRIM(RTRIM(SER_LOT_NO)) IN ('032331','033232')

SELECT * FROM COLORES_CONTROLADOS

select * from HIDESHDR_SQL   
 inner join HIDESLIN_SQL on  HIDESLIN_SQL.FILENO = HIDESHDR_SQL.FILENO
AND	LTRIM(RTRIM(PLOT)) = '401191' 
 AND LTRIM(RTRIM(HIDE))  IN ('0005')
 AND PCOLOR = 'FWLCPT3'


SELECT * FROM ccjobhdr_sql WHERE jobno = '15134  '

SELECT * FROM  RP_SC WHERE LOT = '132782' AND COLOUR = 'FMCKTX7'

SELECT * FROM  RP_SC WHERE TAGNO IN (3798198) order by hide asc

SELECT * FROM	RP_FOLIOS WHERE TAG IN (3788360)

SELECT	* FROM	[PIEL_A_TRANSFERIR]

SELECT	* FROM [PIEL_A_TRANSFERIR_TRANSACCION]

SELECT *
	FROM cccuthst_sql 
	WHERE --LTRIM(RTRIM(COLOUR)) = 'FCNPDX9'   
	--AND	LTRIM(RTRIM(lotno)) = RIGHT('000000' + Ltrim(Rtrim('33231')), 6) 
	--AND LTRIM(RTRIM(hideno))   IN ('0197')
	--AND	
	LTRIM(RTRIM(JOBNO))   = '17917'

SELECT '         ' + RIGHT('000000' + Ltrim(Rtrim('0033231')), 6) 

SELECT * FROM RP_SC WHERE TAGNO = '3795035'
SELECT * FROM RP_Folios WHERE TAG = '14215'
SELECT * FROM ccjobhdr_sql WHERE jobno = '14905'

USE DATA_02
SELECT TOP 1000 D_TIPO_PIEL_LOG,usuario,
PIEL_LOG.*  
FROM PIEL_LOG 
INNER JOIN users_pearl ON PIEL_LOG.K_USUARIO_ALTA = users_pearl.codigo
INNER JOIN TIPO_PIEL_LOG ON PIEL_LOG.K_TIPO_PIEL_LOG=TIPO_PIEL_LOG.K_TIPO_PIEL_LOG
WHERE 
PIEL = 980 
--and lote = 401201   
AND COLOR = 'FMCKTX7' 
order by K_PIEL_LOG


SELECT top 10 * FROM IMLSTRX_SQL	WHERE LTRIM(RTRIM(ord_no)) IN ( '04840477 ') order by trx_dt,trx_tm, ORD_NO desc

SELECT top 10 * FROM IMINVTRX_SQL	WHERE LTRIM(RTRIM(ord_no)) IN ( '04840477 ') order by trx_dt,trx_tm, ORD_NO desc

select top 1000 * --ord_no,lev_no,doc_type, item_no, loc,quantity,doc_ord_no,trx_dt,trx_tm, user_name, A4GLIdentity
from IMINVTRX_SQL 
where  ltrim(rtrim(item_no)) = 'FMCKTX7'    and loc = 'T06' and trx_dt>='20201028' --and doc_type = 'T' AND SEQ_NO <> 0
--and doc_ord_no = '15205'
--and ord_no in ( '4642651','4642598') 
order by trx_dt,trx_tm, ORD_NO desc
--order by ord_no asc
