
USE DATA_02Pruebas
SELECT * FROM [PIEL_A_TRANSFERIR]
SELECT * FROM PIEL_A_TRANSFERIR_TRANSACCION

SELECT D_TIPO_PIEL_LOG,usuario,PIEL_LOG.*  
FROM PIEL_LOG 
INNER JOIN users_pearl ON PIEL_LOG.K_USUARIO_ALTA = users_pearl.codigo
INNER JOIN TIPO_PIEL_LOG ON PIEL_LOG.K_TIPO_PIEL_LOG=TIPO_PIEL_LOG.K_TIPO_PIEL_LOG
/*
TRUNCATE TABLE [PIEL_A_TRANSFERIR]

DELETE	PIEL_A_TRANSFERIR_TRANSACCION
WHERE	K_PIEL_A_TRANSFERIR_TRANSACCION = 2

*/


select * from HIDESHDR_SQL   
 inner join HIDESLIN_SQL on  HIDESLIN_SQL.FILENO = HIDESHDR_SQL.FILENO
AND	LTRIM(RTRIM(PLOT)) = '32782' 
 AND LTRIM(RTRIM(HIDE)) IN   ('0631')

--SELECT * FROM CCJOBHDR_SQL WHERE  LTRIM(RTRIM(jobno)) IN ('11111' ,'11002' )

SELECT  * FROM cccuthst_sql 
WHERE LTRIM(RTRIM(COLOUR)) = 'FMCKTX7'  
AND	LTRIM(RTRIM(lotno)) = '032781' 
 AND LTRIM(RTRIM(hideno))   IN ('0056')
ORDER BY HIDENO ASC

SELECT  * FROM RP_SC
WHERE	LTRIM(RTRIM(COLOUR)) = 'FMCKTX7' 
AND	LTRIM(RTRIM(LOT)) = '32782' 
AND LTRIM(RTRIM(HIDE)) IN   ('0631')




/*
UPDATE cccuthst_sql 
	SET hidesqm = '22.00'
WHERE LTRIM(RTRIM(COLOUR)) = 'FMCKTX7'  
AND	LTRIM(RTRIM(lotno)) = '032781' 
 AND LTRIM(RTRIM(hideno))   IN ('0056')
*/
 
 
 SELECT * FROM RP_SC
 WHERE LTRIM(RTRIM(COLOUR)) = 'FMCKTX7'
 AND	LTRIM(RTRIM(HIDE)) NOT IN (	select HIDE from HIDESHDR_SQL   
									inner join HIDESLIN_SQL on  HIDESLIN_SQL.FILENO = HIDESHDR_SQL.FILENO
									)

SELECT DISTINCT RP_SC.* FROM RP_SC
INNER JOIN [PIEL_A_TRANSFERIR] ON LTRIM(RTRIM(RP_SC.COLOUR)) = [PIEL_A_TRANSFERIR].COLOR AND LTRIM(RTRIM(RP_SC.TAGNO))=[PIEL_A_TRANSFERIR].FOLIO_ORIGEN
WHERE LTRIM(RTRIM(RP_SC.SQF)) <> [PIEL_A_TRANSFERIR].SQF_RECIBIR
AND K_PIEL_A_TRANSFERIR_TRANSACCION = 1

SELECT * FROM [PIEL_A_TRANSFERIR]
WHERE SQF_ENVIAR <> [PIEL_A_TRANSFERIR].SQF_RECIBIR
AND K_PIEL_A_TRANSFERIR_TRANSACCION = 1