
USE [DATA_02Pruebas] 
GO

--ORIGINAL
SELECT DISTINCT * FROM RP_SC WHERE LTRIM(RTRIM(COLOUR)) = 'FMCKTX7' AND LTRIM(RTRIM(TAGNO)) = 2137674 AND LTRIM(RTRIM(LOT)) ='32361' --AND LTRIM(RTRIM(HIDE)) = '0497'

--NUEVO
SELECT TOP 1000 * FROM RP_SC WHERE  LTRIM(RTRIM(COLOUR)) = 'FMCKTX7' AND LTRIM(RTRIM(TAGNO))  = '3785577' --AND LTRIM(RTRIM(LOT))='66421' --AND LTRIM(RTRIM(HIDE)) = '0497' 

--ORIGINAL
SELECT NEXT_DOC_NO FROM 	IMCTLFIL_SQL
--NEXT_DOC_NO
--4246762
--1715937


	select * from IMINVLOC_SQL
--	ID		TAG			STATUS	MACHINE		JOBNO		JOBNO2
--	123564	3785641		A 		-         	-     		NULL

SELECT * FROM	RP_FOLIOS WHERE TAG=3787292
--	ID		TAG			STATUS	MACHINE		JOBNO		JOBNO2
--	123567	3785644		C1 		Table 17     09404 		NULLAmm@


SELECT  machine FROM	CCJOBHDR_SQL WHERE	LTRIM(RTRIM(jobno))=09489
--	jobno	status	colour	colourdesc				machine		datecreated	dateplanned	datecompleted	printedflag	instruct1	instruct2	netsqm		standardsqm	actualsqm	targetutil	customer	patterns	plannedshift	plannedseq	startedflag	comments	lotno	folio
--	09404 	P		MCKTX7 	CHRYSLER MCKINLEY TX7    Table 17    20200129	20200129	NULL			2	                                549.9630	964.8510	NULL		70.00		IRVI02		780			0				0				C		NULL		NULL	3785644


  -- AGREGA A LA LOCACION DESTINO
SELECT * FROM	IMLSMST_SQL WHERE	LTRIM(RTRIM(LOC))='MFP' AND	LTRIM(RTRIM(ITEM_NO))='FMCKTX7' AND	LTRIM(RTRIM(SER_LOT_NO))='033012'
--ORIGINAL: QTY_ON_HAND =164.9000


SELECT * FROM	IMLSMST_SQL WHERE	LTRIM(RTRIM(LOC))='T06' AND	LTRIM(RTRIM(ITEM_NO))='FMCKTX7' AND	LTRIM(RTRIM(SER_LOT_NO))='033012'
--ORIGINAL: QTY_ON_HAND =2322.4000

-- RESTA DE LA LOCACION ORIGEN
SELECT * FROM IMINVLOC_SQL WHERE LTRIM(RTRIM(LOC)) = 'T06' AND	LTRIM(RTRIM(ITEM_NO)) = 'FMCKTX7'
--ORIGINAL: QTY_ON_HAND =7009.9000

SELECT * FROM IMINVLOC_SQL WHERE LTRIM(RTRIM(LOC)) = 'MFP' AND	LTRIM(RTRIM(ITEM_NO)) = 'FMCKTX7'
--ORIGINAL: QTY_ON_HAND =2398.2000


--INSERTA LA TRAnSACCION 

SELECT * FROM IMLSTRX_SQL	WHERE LTRIM(RTRIM(ord_no)) IN ( '4454018  ')


SELECT * FROM IMINVTRX_SQL WHERE LTRIM(RTRIM(ord_no)) IN ( '4454018')

SELECT TOP 3 * FROM HIDESHDR_SQL WHERE FILENO = '200213113255T1000001'

SELECT  * FROM HIDESLIN_SQL WHERE FILENO = '200213113255T1000001'



--==================PARA TRANSACCIONES SIN ORDEN=================================================
--USE DATA_02
--GO

SELECT DISTINCT  IMINVTRX_SQL.lev_no,IMINVTRX_SQL.trx_dt,IMINVTRX_SQL.trx_tm, IMINVTRX_SQL.ord_no, IMINVTRX_SQL.item_no,ser_lot_no,loc, doc_ord_no, doc_type ,IMLSTRX_SQL.trx_qty,user_name
from IMINVTRX_SQL 
inner join IMLSTRX_SQL on IMLSTRX_SQL.ord_no = IMINVTRX_SQL.ord_no
where IMINVTRX_SQL.trx_dt>='20200301' /*and IMINVTRX_SQL.lev_no='0' and loc = 'T38'*/  and doc_type='T' --AND LOC='T16'
  and IMLSTRX_SQL.trx_dt>='20200526' -- and IMLSTRX_SQL.lev_no='0' 
  --AND IMLSTRX_SQL.trx_qty = 21.5000
  AND    ser_lot_no='         033101' 
  AND DOC_ORD_NO='12063   '     
  order by IMINVTRX_SQL.trx_dt, trx_tm asc

SELECT D_TIPO_PIEL_LOG,usuario,PIEL_LOG.*  
FROM PIEL_LOG 
INNER JOIN TIPO_PIEL_LOG ON PIEL_LOG.K_TIPO_PIEL_LOG=TIPO_PIEL_LOG.K_TIPO_PIEL_LOG
INNER JOIN users_pearl ON PIEL_LOG.K_USUARIO_ALTA = users_pearl.codigo
WHERE  ORDEN_DESTIDO=12335
 and	FOLIO_ORIGEN =3789271-- OR FOLIO_DESTINO = '3789148'
ORDER BY F_ALTA ASC

select * from RP_SC where TAGNO=3789271

select * from RP_Folios where TAG = 3789271

 /*
update RP_Folios
	set MACHINE = 'Table 39',
		JOBNO = '12374'
WHERE TAG = 3789271
*/

select * from CCJOBHDR_SQL where jobno = 12374

SELECT  *
FROM cccuthst_sql 
where jobno = 12374

SELECT * FROM IMINVTRX_SQL WHERE ord_no IN (04376600) 
 --and lev_no = 0
SELECT * FROM IMLSTRX_SQL WHERE   ord_no IN (04376508)     --ser_lot_no='         032941' and IMLSTRX_SQL.trx_dt>='20200225'  AND (IMLSTRX_SQL.trx_qty = 21.5000 OR IMLSTRX_SQL.trx_qty = 43.0000)
ORDER BY ORD_NO DESC
 --and lev_no = 0

 SELECT D_TIPO_PIEL_LOG,usuario,PIEL_LOG.*  
FROM PIEL_LOG 
INNER JOIN TIPO_PIEL_LOG ON PIEL_LOG.K_TIPO_PIEL_LOG=TIPO_PIEL_LOG.K_TIPO_PIEL_LOG
INNER JOIN users_pearl ON PIEL_LOG.K_USUARIO_ALTA = users_pearl.codigo

--=====================================================================================

