
USE DATA_02Pruebas
SELECT * FROM [PIEL_A_TRANSFERIR]
SELECT * FROM PIEL_A_TRANSFERIR_TRANSACCION
/*
TRUNCATE TABLE [PIEL_A_TRANSFERIR]

DELETE	PIEL_A_TRANSFERIR_TRANSACCION
WHERE	K_PIEL_A_TRANSFERIR_TRANSACCION = 2

*/


select * from HIDESHDR_SQL   
 inner join HIDESLIN_SQL on  HIDESLIN_SQL.FILENO = HIDESHDR_SQL.FILENO
AND	LTRIM(RTRIM(PLOT)) = '32782' 
 AND LTRIM(RTRIM(HIDE)) IN   ('0631')

--SELECT * FROM CCJOBHDR_SQL WHERE  LTRIM(RTRIM(jobno)) IN ('11111' ,'11002' )

SELECT  * FROM cccuthst_sql 
WHERE LTRIM(RTRIM(COLOUR)) = 'FMCKTX7'  
AND	LTRIM(RTRIM(lotno)) = '032782' 
 AND LTRIM(RTRIM(hideno))   IN ('0631')
ORDER BY HIDENO ASC

/*
UPDATE cccuthst_sql 
	SET hidesqm = '20.30'
WHERE LTRIM(RTRIM(COLOUR)) = 'FMCKTX7'  
AND	LTRIM(RTRIM(lotno)) = '032782' 
 AND LTRIM(RTRIM(hideno))   IN ('0631')
 /*
 --================================================================
 
--  SELECT  * FROM RP_SC_FOLIO_STATUS_XX
-- WHERE	LTRIM(RTRIM(COLOUR)) = 'FMCKTX7' 
--AND	LTRIM(RTRIM(LOT)) = '32681' 
-- AND LTRIM(RTRIM(HIDE)) IN   ('0016')

SELECT  * FROM RP_SC
WHERE	LTRIM(RTRIM(COLOUR)) = 'FMCKTX7' 
AND	LTRIM(RTRIM(LOT)) = '32782' 
AND LTRIM(RTRIM(HIDE)) IN   ('0631')

DECLARE @VP_SQF_RECIBIR				VARCHAR(20)	
SET @VP_SQF_RECIBIR = CONVERT(DECIMAL(13,2),'40') - CONVERT(DECIMAL(13,2),'20')

SELECT @VP_SQF_RECIBIR
