
USE [DATA_02Pruebas] 
GO
	--UPDATE DATA_02Pruebas.DBO.RP_SC 
	--SET TYPE = 'D'
	--WHERE TAGNO IN ( 3798327) 
	--AND ID IN (5122787, 5128937, 5128940 )
	
	SELECT top 10000 D_TIPO_PIEL_LOG, 
			(CASE WHEN usuario IS NULL THEN (	SELECT CONCAT(EP_NOMBRE, ' ', EP_APELLIDO_PATERNO) 
												FROM HOWE.dbo.VISTA_GAFETES (NOLOCK)
												WHERE EN_NUM_EMP = K_USUARIO_ALTA)
				ELSE usuario END) AS RESPONSABLE, 
			PIEL_LOG.*
	FROM PIEL_LOG 
	LEFT JOIN users_pearl ON PIEL_LOG.K_USUARIO_ALTA = users_pearl.codigo
	INNER JOIN TIPO_PIEL_LOG ON PIEL_LOG.K_TIPO_PIEL_LOG = TIPO_PIEL_LOG.K_TIPO_PIEL_LOG
	WHERE 
	LOTE IN (401051    )    
	AND  PIEL IN  ( 19, 124)
	ORDER BY piel, k_piel_log DESC

	--SELECT	TOP 1 TAG	
	--FROM RP_Folios  INNER JOIN RP_SC ON TAG=TAGNO 
	--WHERE STATUS='B' AND COLOUR = 'FMCKTX7'
	---- FWLPAX7   
	--SELECT * FROM RP_Folios WHERE TAG IN ( 3793142, 2137674) 

	SELECT TOP 1  STATUS,
					TAG
					FROM RP_FOLIOS
					INNER JOIN RP_SC ON TAG = TAGNO
					WHERE RP_SC.TAGNO = 3793142

	SELECT * FROM COLORES_CONTROLADOS

	SELECT * -- SUM(CONVERT(DECIMAL(13,2), SQF)) 
	FROM RP_SC 
	WHERE TAGNO IN ( 3793136) AND LOT = '401051' 
	AND CONVERT(INT, HIDE) IN (19, 124)  ORDER BY HIDE

	SELECT * FROM RP_SC 
	WHERE TAGNO IN ( 3798086) AND LOT = '401051' 
	AND CONVERT(INT, HIDE) IN (19, 124)  ORDER BY HIDE

	SELECT * FROM RP_SC WHERE TAGNO IN ( 3798086) AND TYPE <> 'D'
	SELECT * FROM RP_SC WHERE TAGNO IN ( 3798086) AND TYPE = 'D' ORDER BY HIDE 

	--UPDATE RP_SC SET TYPE = 'C' WHERE ID = 6270355

	--DELETE DATA_02PRUEBAS.DBO.RP_SC WHERE TAGNO IN ( 3798533) AND TYPE = 'D'
	--DELETE DATA_02PRUEBAS.DBO.RP_SC_PRT  WHERE TAG IN ( 3798533)

	SELECT SUM(CONVERT(DECIMAL(13,2), SQF)) FROM RP_SC WHERE TAGNO IN ( 3798533) -- AND HIDE NOT IN ( '0242', '0240' )

	SELECT * FROM RP_SC_PRT 

	SELECT * FROM RP_Folios WHERE TAG = 3798086

	SELECT * FROM ccjobhdr_sql WHERE jobno = '17882' 

	SELECT * FROM CCCUTHST_SQL WHERE jobno = '17882' --AND hideno IN ( '0102' )

	--UPDATE DATA_02Pruebas.DBO.CCCUTHST_SQL 
	--SET hidesqm = 0
	--WHERE jobno = '18147' AND hideno IN ( '0243' )

	SELECT RIGHT('000000' + '33561', 6)

	USE DATA_02PRUEBAS
	SELECT TOP 100 * FROM IMINVTRX_SQL ORDER BY A4GLIdentity DESC

	-- SQF DEV: 34.30
	SELECT * FROM	IMLSMST_SQL	WHERE	LTRIM(RTRIM(SER_LOT_NO)) IN ('401051    ') AND item_no = 'FWLCPT3   ' AND LOC = 'MHI'
	-- CANTIDAD :8761.9000 

	SELECT * FROM	IMLSMST_SQL	WHERE	LTRIM(RTRIM(SER_LOT_NO)) IN ('401051') AND item_no = 'FWLCPT3' AND LOC = 'T35'
	-- CANTIDAD :152.6 - 50.30 = 102.3

	SELECT TOP 10 * FROM	IMINVLOC_SQL WHERE	LTRIM(RTRIM(loc)) IN ('MHI')
	SELECT TOP 10 * FROM IMLSTRX_SQL ORDER BY A4GLIDENTITY DESC

	SELECT * FROM IMLSTRX_SQL WHERE ord_no = 4911481    
	SELECT * FROM IMINVTRX_SQL WHERE ord_no = 4911481     
--=====================================================================================

