
USE [DATA_02Pruebas] 
GO

--ORIGINAL
SELECT DISTINCT * FROM RP_SC WHERE LTRIM(RTRIM(COLOUR)) = 'FMCKTX7' AND LTRIM(RTRIM(TAGNO)) = 2137674 AND LTRIM(RTRIM(LOT)) ='32361' --AND LTRIM(RTRIM(HIDE)) = '0497'

--NUEVO
SELECT TOP 1000 * FROM RP_SC WHERE  LTRIM(RTRIM(COLOUR)) = 'FMCKTX7' AND LTRIM(RTRIM(TAGNO))  = '3785577' --AND LTRIM(RTRIM(LOT))='66421' --AND LTRIM(RTRIM(HIDE)) = '0497' 

SELECT top 1000 * FROM pearl_log  order by ckey desc 
                
SELECT TOP 1000 * FROM RP_SC  order by tagno desc	
--test
--3785649	

 --prd
----3786763
--use DATA_02
select * from users_pearl WHERE USUARIO = 'VIVIANAC'
select * from users_pearl WHERE USUARIO = 'MANUELG'
--	DELETE FROM pearl_log WHERE screen_opt = 'Transactions' AND user_name = 'franciscoe'

--ORIGINAL
SELECT NEXT_DOC_NO FROM 	IMCTLFIL_SQL
--NEXT_DOC_NO
--4246762
--1715937

SELECT * FROM TIPO_PIEL_LOG

SELECT * FROM PIEL_LOG WHERE K_TIPO_PIEL_LOG=7

SELECT D_TIPO_PIEL_LOG,usuario,PIEL_LOG.*  
FROM PIEL_LOG 
INNER JOIN users_pearl ON PIEL_LOG.K_USUARIO_ALTA = users_pearl.codigo
INNER JOIN TIPO_PIEL_LOG ON PIEL_LOG.K_TIPO_PIEL_LOG=TIPO_PIEL_LOG.K_TIPO_PIEL_LOG
WHERE  LOTE = 33002 AND PIEL IN ( 1033)

----SELECT * FROM RP_SC WHERE TAGNO IN (3787754) AND HIDE = '0483'
--SELECT * FROM RP_SC WHERE TAGNO IN (3787754,3787769,2137674) AND HIDE IN ( '0481', '0483') AND LOT= '33002'
--SELECT DISTINCT * FROM  RP_Folios WHERE TAG IN (3787754,3787769)

-- SI SON MAS DE UNA PIEL Y QUIERE IMPRIMIR EL FORMATO DE DEVOLUCION Y EXTRAS
SELECT * FROM  RP_SC WHERE TAGNO  IN (3787880,3787854)

SELECT * FROM	RP_FOLIOS WHERE TAG IN (3787880,3787854)

	select * from IMINVLOC_SQL
--	ID		TAG			STATUS	MACHINE		JOBNO		JOBNO2
--	123564	3785641		A 		-         	-     		NULL

SELECT * FROM	RP_FOLIOS WHERE TAG=3787292
--	ID		TAG			STATUS	MACHINE		JOBNO		JOBNO2
--	123567	3785644		C1 		Table 17     09404 		NULLAmm@


SELECT  machine FROM	CCJOBHDR_SQL WHERE	LTRIM(RTRIM(jobno))=09489
--	jobno	status	colour	colourdesc				machine		datecreated	dateplanned	datecompleted	printedflag	instruct1	instruct2	netsqm		standardsqm	actualsqm	targetutil	customer	patterns	plannedshift	plannedseq	startedflag	comments	lotno	folio
--	09404 	P		MCKTX7 	CHRYSLER MCKINLEY TX7    Table 17    20200129	20200129	NULL			2	                                549.9630	964.8510	NULL		70.00		IRVI02		780			0				0				C		NULL		NULL	3785644


  -- AGREGA A LA LOCACION DESTINO
SELECT * FROM	IMLSMST_SQL WHERE	LTRIM(RTRIM(LOC))='MQU' AND	LTRIM(RTRIM(ITEM_NO))='FMCKTX7' AND	LTRIM(RTRIM(SER_LOT_NO))='032141'
--ORIGINAL: QTY_ON_HAND =0.0000


-- RESTA DE LA LOCACION ORIGEN
SELECT * FROM IMINVLOC_SQL WHERE LTRIM(RTRIM(LOC)) = 't17' AND	LTRIM(RTRIM(ITEM_NO)) = 'FMCKTX7'
--ORIGINAL: QTY_ON_HAND =5117.0000

--INSERTA LA TRAnSACCION 
SELECT  * FROM IMINVTRX_SQL WHERE LTRIM(RTRIM(ord_no))= '10559'
SELECT * FROM IMLSTRX_SQL	WHERE LTRIM(RTRIM(ord_no)) IN ( '4346850')


SELECT * FROM IMINVTRX_SQL WHERE LTRIM(RTRIM(Id_no)) IN ( 'I043468420000000000000000000')

SELECT TOP 3 * FROM HIDESHDR_SQL WHERE FILENO = '200213113255T1000001'

SELECT  * FROM HIDESLIN_SQL WHERE FILENO = '200213113255T1000001'



--==================PARA TRANSACCIONES SIN ORDEN=================================================
--USE DATA_02
--GO
select * --ord_no,lev_no,doc_type, item_no, loc,quantity,doc_ord_no,trx_dt,trx_tm, user_name, A4GLIdentity
from IMINVTRX_SQL 
where trx_dt>='20200226'   and doc_type='T' AND DOC_ORD_NO='10675   '
order by ord_no asc

SELECT top 300 IMINVTRX_SQL.lev_no,IMINVTRX_SQL.trx_dt,IMINVTRX_SQL.trx_tm, IMINVTRX_SQL.ord_no, IMINVTRX_SQL.item_no,ser_lot_no,loc, doc_ord_no, doc_type ,IMLSTRX_SQL.trx_qty,user_name
from IMINVTRX_SQL 
inner join IMLSTRX_SQL on IMLSTRX_SQL.ord_no = IMINVTRX_SQL.ord_no
where IMINVTRX_SQL.trx_dt>='20200302' /*and IMINVTRX_SQL.lev_no='0' and loc = 'T38'*/  and doc_type='T' --AND LOC='T38'
  and IMLSTRX_SQL.trx_dt>='20200302'  and IMLSTRX_SQL.lev_no='0' 
  --AND IMLSTRX_SQL.trx_qty = 21.5000
  --AND    ser_lot_no='         032941'      
  order by IMINVTRX_SQL.trx_dt asc

  SELECT D_TIPO_PIEL_LOG,usuario,PIEL_LOG.*  
FROM PIEL_LOG 
INNER JOIN TIPO_PIEL_LOG ON PIEL_LOG.K_TIPO_PIEL_LOG=TIPO_PIEL_LOG.K_TIPO_PIEL_LOG
INNER JOIN users_pearl ON PIEL_LOG.K_USUARIO_ALTA = users_pearl.codigo
WHERE  LOTE=32641 AND LOCACION_DESTINO = 'T03' AND ORDEN_DESTIDO=10771

select * from RP_SC where TAGNO=3786904

select * from CCJOBHDR_SQL where jobno = 11358

SELECT * FROM IMINVTRX_SQL WHERE ord_no IN (04376600) 
 --and lev_no = 0
SELECT * FROM IMLSTRX_SQL WHERE   ord_no IN (04376508)     --ser_lot_no='         032941' and IMLSTRX_SQL.trx_dt>='20200225'  AND (IMLSTRX_SQL.trx_qty = 21.5000 OR IMLSTRX_SQL.trx_qty = 43.0000)
ORDER BY ORD_NO DESC
 --and lev_no = 0

 SELECT D_TIPO_PIEL_LOG,usuario,PIEL_LOG.*  
FROM PIEL_LOG 
INNER JOIN TIPO_PIEL_LOG ON PIEL_LOG.K_TIPO_PIEL_LOG=TIPO_PIEL_LOG.K_TIPO_PIEL_LOG
INNER JOIN users_pearl ON PIEL_LOG.K_USUARIO_ALTA = users_pearl.codigo


SELECT PIEL_LOG.*  
FROM PIEL_LOG 
WHERE    K_USUARIO_ALTA = 0
 --UPDATE  IMLSTRX_SQL 
	--SET trx_qty = 21.5000
 --WHERE   ord_no IN (4375667)

--use DATA_02
--go
--update IMINVTRX_SQL		
--		set doc_ord_no = '10407'
--WHERE ord_no = 4370286
-- and lev_no = 0

--select * from pearl_log where cdate = '02/03/2020' and ctime > 090000 

--use DATA_02
--go
--SELECT * FROM IMLSMST_SQL
--WHERE	LTRIM(RTRIM(LOC))='MHI'
--		AND		LTRIM(RTRIM(ITEM_NO))='FMCKTX7'
--		AND		LTRIM(RTRIM(SER_LOT_NO))='032941'
		
--UPDATE	IMLSMST_SQL
--		SET		
--				QTY_ON_HAND =  QTY_ON_HAND + 21.50
--		WHERE	LTRIM(RTRIM(LOC))='MHI'
--		AND		LTRIM(RTRIM(ITEM_NO))='FMCKTX7'
--		AND		LTRIM(RTRIM(SER_LOT_NO))='032941'

--SELECT * FROM IMINVLOC_SQL
--		WHERE	LTRIM(RTRIM(LOC))='MHI'
--		AND		LTRIM(RTRIM(ITEM_NO))='FMCKTX7'
		
--UPDATE	IMINVLOC_SQL
--		SET		
--				QTY_ON_HAND =  QTY_ON_HAND + 21.50
--		WHERE	LTRIM(RTRIM(LOC))='MHI'
--		AND		LTRIM(RTRIM(ITEM_NO))='FMCKTX7'
--=====================================================================================

