
USE DATA_02 --Pruebas
SELECT * FROM [PIEL_A_TRANSFERIR]
SELECT * FROM PIEL_A_TRANSFERIR_TRANSACCION

SELECT D_TIPO_PIEL_LOG,usuario,PIEL_LOG.*  
FROM PIEL_LOG 
INNER JOIN users_pearl ON PIEL_LOG.K_USUARIO_ALTA = users_pearl.codigo
INNER JOIN TIPO_PIEL_LOG ON PIEL_LOG.K_TIPO_PIEL_LOG=TIPO_PIEL_LOG.K_TIPO_PIEL_LOG
/*
USE DATA_02Pruebas
TRUNCATE TABLE [PIEL_A_TRANSFERIR]


DELETE	PIEL_A_TRANSFERIR_TRANSACCION
WHERE	K_PIEL_A_TRANSFERIR_TRANSACCION = 2

*/


select * from HIDESHDR_SQL   
 inner join HIDESLIN_SQL on  HIDESLIN_SQL.FILENO = HIDESHDR_SQL.FILENO
AND	LTRIM(RTRIM(PLOT)) = '33012' 
 AND LTRIM(RTRIM(HIDE))   IN (SELECT HIDE FROM RP_SC WHERE TAGNO = 3788343)

--SELECT * FROM CCJOBHDR_SQL WHERE  LTRIM(RTRIM(jobno)) IN ('11111' ,'11002' )
USE DATA_02 --Pruebas
SELECT  * FROM cccuthst_sql 
WHERE LTRIM(RTRIM(COLOUR)) = 'FMCKVT9'  
AND	LTRIM(RTRIM(lotno)) = '033051' 
 AND LTRIM(RTRIM(hideno))   IN ('0410')
ORDER BY HIDENO ASC

SELECT DISTINCT  * FROM cccuthst_sql 
WHERE LTRIM(RTRIM(COLOUR)) = 'FMCKTX7'  
AND	LTRIM(RTRIM(lotno)) = '033012' 
 AND LTRIM(RTRIM(hideno))   IN (SELECT HIDE FROM RP_SC WHERE TAGNO = 3788360)
ORDER BY HIDENO ASC

SELECT * FROM RP_SC WHERE TAGNO = 3788349

SELECT  * FROM RP_SC
WHERE	LTRIM(RTRIM(COLOUR)) = 'FMCKTX7' 
AND	LTRIM(RTRIM(LOT)) = '33021' 
AND LTRIM(RTRIM(HIDE)) IN   ('0223')

--UPDATE RP_SC
--SET TAGNO = 3788514
--WHERE	LTRIM(RTRIM(COLOUR)) = 'FMCKTX7' 
--AND	LTRIM(RTRIM(LOT)) = '33021' 
--AND LTRIM(RTRIM(HIDE)) IN   ('0223')
--AND TAGNO = 3788491

/*
USE DATA_02Pruebas
UPDATE cccuthst_sql 
	SET hidesqm = '15.00'
WHERE LTRIM(RTRIM(COLOUR)) = 'FMCKTX7'  
AND	LTRIM(RTRIM(lotno)) = '033012' 
AND LTRIM(RTRIM(hideno))   IN ('0227')
*/


 --USE DATA_02Pruebas
 --IF (	SELECT COUNT(*) FROM sys.table_types
	--						WHERE name = 'TVPParamtest' AND schema_id = 1	) = 0
	--						CREATE TYPE dbo.TVPParamtest AS TABLE(	COLOR		VARCHAR(20),
	--															LOTE		VARCHAR(20),
	--															SQF			VARCHAR(20)	)
				

 USE DATA_02Pruebas

declare @result int

execute [dbo].[PG_PM_TEST_TABLA] 0,0,@result out

select @result

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_PM_TEST_TABLA]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_PM_TEST_TABLA]
GO
-- EXECUTE   [dbo].[PG_PM_TEST_TABLA] 0,0, 'B' , 'FCMKDX9' 

CREATE PROCEDURE [dbo].[PG_PM_TEST_TABLA]
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================
	--@TBL_TOTAL_SQF_X_LOTE		TVPParamtest READONLY,
	-- ===========================
	@OU_RESULTADO				INT OUTPUT
AS
	-- ///////////////////////////////////////////
	--DROP TABLE test

	
	--select COLOR,LOTE,SQF into test
	--from @TBL_TOTAL_SQF_X_LOTE
	
	--DECLARE @SQF VARCHAR(10)
	--SELECT @SQF = SQF  FROM test

	SET @OU_RESULTADO = 1

	-- ////////////////////////////////////////////////////////////////////
	-- ////////////////////////////////////////////////////////////////////

GO

