
USE [DATA_02] 
GO


SELECT * FROM PIEL_CLASIFICACION

SELECT * FROM PIEL_CLASIFICADA_PORCENTAJE

/*
	DELETE FROM PIEL_CLASIFICADA_PORCENTAJE
*/

SELECT *
FROM RP_SC 
WHERE	LTRIM(RTRIM(COLOUR)) = 'FMCKTX7' 
AND		LTRIM(RTRIM(LOT))='33162' 
AND		CONVERT(INTEGER,LTRIM(RTRIM(hide))) BETWEEN 44 AND 54		--('1203','1204','1205','1206','1207','1208') 
--AND K_CLASIFICACION <> 0
ORDER BY HIDE ASC

/*

UPDATE RP_SC
SET  K_CLASIFICACION = 0
WHERE	LTRIM(RTRIM(COLOUR)) = 'FMCKTX7' 
AND		LTRIM(RTRIM(LOT))='33162' 
AND		CONVERT(INTEGER,LTRIM(RTRIM(hide))) BETWEEN 44 AND 54

*/



SELECT * FROM RP_SC
WHERE LTRIM(RTRIM(COLOUR)) = 'FMCKTX7' 
AND		LTRIM(RTRIM(LOT))='33101' 
AND HIDE = '0662'
--AND K_CLASIFICACION <> 0

/*

UPDATE RP_SC
SET  K_CLASIFICACION = 0
WHERE LTRIM(RTRIM(COLOUR)) = 'FMCKTX7' 
AND		LTRIM(RTRIM(LOT))='33101' 
AND HIDE = '0662'

*/


--===========================================


USE [DATA_02Pruebas] 
GO

SELECT * FROM RP_SC
WHERE TAGNO = 3788319


UPDATE RP_SC
	SET K_CLASIFICACION = 0
WHERE TAGNO = 3788319
AND LTRIM(RTRIM(HIDE)) = '0899 '
