

 --SE RESPALDA PIELES QUE HAY ACTUALMENTE EN LA TABLA RP_SC EN TABLA RP_SC_HIDE_DELETE 
--INSERT INTO RP_SC_HIDE_DELETE( 
--		[CDATE],[COLOUR],[LOT],[HIDE],[SQF],[TAGNO],[YARDAS],[YLB],[PESO],[TYPE],[MOVEMENT],[K_CLASIFICACION]
--		)
--SELECT GETDATE(),[COLOUR],[LOT],[HIDE],[SQF],[TAGNO],[YARDAS],[YLB],[PESO],[TYPE],MOVEMENT,[K_CLASIFICACION] 
--FROM RP_SC (NOLOCK) 
--WHERE LTRIM(RTRIM(COLOUR)) = 'FMCKPD2'
--AND MOVEMENT IN ('MOB', 'MHI') 


------DELETE RP_SC WHERE LTRIM(RTRIM(COLOUR)) = 'FMCKPD2'AND MOVEMENT IN ('MOB', 'MHI') 

-- SE CARGAN LAS PIELES DE LOS DETALLADOS
--INSERT INTO RP_SC( 
--		[CDATE],[COLOUR],[LOT],[HIDE],[SQF],[TAGNO],[YARDAS],[YLB],[PESO],[TYPE],[MOVEMENT],[K_CLASIFICACION]
--		)
--SELECT GETDATE(),LTRIM(RTRIM([COLOUR])),LTRIM(RTRIM([LOT])),LTRIM(RTRIM([HIDE])),LTRIM(RTRIM([SQF])),3881658, [YARDAS],[YLB],[PESO],'C','MOB',[K_CLASIFICACION]
--FROM RP_SC_FOLIO_TYPE_2
--WHERE LTRIM(RTRIM(COLOUR)) = 'FMCKPD2' 
--	AND TAGNO IN ( 3791601,3791602, 3791603, 3791604, 3791611 )


	SELECT * --[COLOUR], [LOT], [HIDE], [SQF], 3772650, 'C', 'MHI'
	FROM RP_SC_FOLIO_TYPE_2 (NOLOCK)
	WHERE LTRIM(RTRIM(COLOUR)) = 'FMCKPD2' 
	AND TAGNO IN ( 3791601,3791602, 3791603, 3791604, 3791611 )
	ORDER BY LOT, HIDE

	SELECT  LOT, HIDE, COUNT(*) AS N_DUPLICADA
	FROM RP_SC_FOLIO_TYPE_2 (NOLOCK)
	WHERE LTRIM(RTRIM(COLOUR)) = 'FMCKPD2' 
	AND TAGNO IN ( 3791601,3791602, 3791603, 3791604, 3791611 )
	GROUP BY  LOT, HIDE 
	HAVING COUNT(*)>1
	ORDER BY LOT, HIDE

	-- SE OBTIENE EL FOLIO DONDE SE VAN A CARGAR LAS PIELES
	SELECT * 
	FROM RP_SC 
	WHERE COLOUR = 'FMCKPD2' AND MOVEMENT IN ( 'MOB', 'MHI' )
	AND TAGNO = 3881658

	SELECT * FROM RP_Folios WHERE TAG = 3881658
